### ISSUE TITLE
Single Tuner utilization in .53

### ISSUE THREAD

**Issue by lulsas** [craigmox/cetonproxy#1]
First thanks for making this. I started out using .53 and it was working on and off. I didn't find a pattern but one of the things I did notice is that if a tuner was in use, and another broadcast stream was requested it would always take over the first tuner leaving the other three unused. If I disabled 1 it would use two, but the same thing, if a second request came in that request took over the tuner and it wouldn't utilize three or four. I downgraded to .52 and it's been working great. Only issue so far is some channels (not sure what is common to them yet) would error out trying to stream and if you back out (in Plex) after the hang it doesn't release the tuner. More of a Plex failure I think but it would be cool if you could kill a stream from the proxy software interface.  

I'm new so let me know if I didn't report something right. Again, thanks for making this.

**Comment by craigmox** [comment]
Thanks for the report.  I use NextPVR primarily, and not Plex, so I didn't notice the problem with it taking over tuner 1 repeatedly.  I will fix it soon.  

I will also try to add a button to kill an active tuner stream.  I have also seen NextPVR hang onto a stream forever, so it very possibly could be a cetonproxy issue.  I will keep trying to track this down.

**Comment by lulsas** [comment]
Thanks for responding so quickly. Check your Paypal and have a sixer on me. :-)

**Comment by craigmox** [comment]
Thanks I appreciate it!  I just put up a new version that should fix both issues you brought up.  I did not add a button to stop a stream.  My hope is that it's never needed if it closes the streams when it's supposed to.
