### ISSUE TITLE
How do you update the Ceton firmware?

### ISSUE THREAD

**Issue by BernardHymmen** [craigmox/cetonproxy#14]
Sorry this isn't exactly an issue with cetonproxy, but my general Internet searches weren't coming up with any answers, so I'm not sure where else to go...

I've got a Ceton InfiniTV 4 PCIe that I rescued from my recently deceased Windows Media Center (；′⌒`)  and I thought I'd give cetonproxy + Plex on my Windows 10 PC a try.  The physical installation of the card and the software installation of the drivers all seemed to work just fine, but the firmware version on my card turns out to be just 1.1.8.2 so I know I need to update that.  I downloaded the three *.image files just fine but how do I actually get those files onto my card?  I don't see any way to do it through the Ceton Diagnostics Tool that installed with the drivers.  I'm comfortable with Windows command line tools, PowerShell and all that, I just don't know what I need to run and how.  Any suggestions?

**Comment by mike015pgh** [comment]
a way to upgrade your firmware is to use the web interface (to be honest I have not tried it)
typically 192.168.200.1 for PCIe tuners and 192.168.180.1 for USB tuners
from there go to the SYSTEM tab
If you scroll to the bottom you should see an option to upgrade the firmware.
good luck, hope it works out. 

![Screenshot from 2020-10-09 22-43-20](https://user-images.githubusercontent.com/19741979/95643966-fb1cea80-0a80-11eb-94f0-b879e5e8a2c1.png)
![Screenshot from 2020-10-09 22-43-52](https://user-images.githubusercontent.com/19741979/95643973-0a9c3380-0a81-11eb-8b4f-2e37d24ff960.png)

in windows I used to use the ceton diagnositics tool program (don't remember the actual name) there was a upgrade option there as well. I am on linux now and dont have access to the program any more.

**Comment by BernardHymmen** [comment]
Thanks for the tip!  Yes, that worked out great.  I did all three firmware updates in succession (BTW, for anyone who needs to do this, a machine reboot is required between each one) and everything worked out fine.  My card saw all the channels on my cable service (Ziply fiber in Seattle, FWIW) without any issues and Plex detected the the card as an HDHomeRun just as advertised.  I was actually surprised at how smoothly it all worked out for me!  I do occasionally see some freezing and buffering, but I have no way of knowing what's to blame for that cetonproxy, Plex, or my home network/computer (which is pretty beefy so I doubt it's that).

The facility for updating firmware through the Ceton Diagnostics Tool is effectively dead.  The system is there, but it's clearly looking out into the great beyond for files on a server that was probably turned off years ago.  No point in "try[ing] again later" as the UI optimistically suggests.
